---
title: "DataTransformation"
author: "Armando F"
date: "9/30/2019"
output: html_document
---

```{r set-up}
library(nycflights13)
library(tidyverse)
```

```{r 5.1}
View(flights)
```

```{r 5.2}
filter(flights, month == 1, day == 1)
jan1 <- filter(flights, month == 1, day == 1)
(dec25 <- filter(flights, month == 12, day == 25))
near(sqrt(2) ^ 2,  2)
near(1 / 49 * 49, 1)
filter(flights, month == 11 | month == 12)
nov_dec <- filter(flights, month %in% c(11, 12))
filter(flights, !(arr_delay > 120 | dep_delay > 120))
filter(flights, arr_delay <= 120, dep_delay <= 120)

```

```{r 5.2.4 excercises}
#1 Find all flights that

#Had an arrival delay of two or more hours
filter(flights, arr_delay <= 120 | arr_delay== 120)
#Flew to Houston (IAH or HOU)
filter(flights, dest == "IAH" | dest== "HOU" )
#Were operated by United, American, or Delta
filter(flights, carrier== "UA" | carrier== "AA" | carrier== "DL")
#Departed in summer (July, August, and September)
filter(flights, month == 6 | month==7 | month==8)
#Arrived more than two hours late, but didn’t leave late
filter(flights, arr_delay <=120|dep_delay==0)
#Were delayed by at least an hour, but made up over 30 minutes in flight
filter(flights, dep_delay <=60|dep_delay==60|air_time<=30)
#Departed between midnight and 6am (inclusive)
filter(flights, dep_time>=0 & dep_time<=360)
#2 Another useful dplyr filtering helper is between(). What does it do? Can you use it to simplify the code needed to answer the previous challenges?
filter(flights, between(dep_time, 0, 360))
#3 How many flights have a missing dep_time? What other variables are missing? What might these rows represent?
filter(flights, is.na(dep_time))
  
#4 Why is NA ^ 0 not missing? Why is NA | TRUE not missing? Why is FALSE & NA not missing? Can you figure out the general rule? (NA * 0 is a tricky counterexample!)


```


```{r 5.3}
df <- tibble(x = c(1, NA, 3))
df <- tibble(x = c(5, 2, NA))
arrange(df, x)
arrange(df, desc(x))
```
```{r 5.3.1 exercises}
#1 How could you use arrange() to sort all missing values to the start? (Hint: use is.na()).

#2 Sort flights to find the most delayed flights. Find the flights that left earliest.

#3 Sort flights to find the fastest flights.

#4 Which flights travelled the longest? Which travelled the shortest?

```


```{r 5.4}
select(flights, year, month, day)
select(flights, -(year:day))
rename(flights, tail_num = tailnum)
select(flights, time_hour, air_time, everything())
```
```{r 5.4.1 exercises}
# 1. Brainstorm as many ways as possible to select dep_time, dep_delay, arr_time, and arr_delay from flights.

# 2. What happens if you include the name of a variable multiple times in a select() call?

# 3. What does the one_of() function do? Why might it be helpful in conjunction with this vector?

# 4. Does the result of running the following code surprise you? How do the select helpers deal with case by default? How can you change that default?
```

```{r 5.5}
flights_sml <- select(flights, 
  year:day, 
  ends_with("delay"), 
  distance, 
  air_time
)
mutate(flights_sml,
  gain = dep_delay - arr_delay,
  speed = distance / air_time * 60
)

mutate(flights_sml,
  gain = dep_delay - arr_delay,
  hours = air_time / 60,
  gain_per_hour = gain / hours
)

transmute(flights,
  gain = dep_delay - arr_delay,
  hours = air_time / 60,
  gain_per_hour = gain / hours
)

transmute(flights,
  dep_time,
  hour = dep_time %/% 100,
  minute = dep_time %% 100
)

(x <- 1:10)

lag(x)

lead(x)

cumsum(x)

cummean(x)

y <- c(1, 2, 2, NA, 3, 4)
min_rank(y)
min_rank(desc(y))

row_number(y)

dense_rank(y)

percent_rank(y)

cume_dist(y)
```

```{r 5.5.2 exercises}
#1. Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers. Convert them to a more convenient representation of number of minutes since midnight.

#2. Compare air_time with arr_time - dep_time. What do you expect to see? What do you see? What do you need to do to fix it?

#3. Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?

#4. Find the 10 most delayed flights using a ranking function. How do you want to handle ties? Carefully read the documentation for min_rank().

#5. What does 1:3 + 1:10 return? Why?

#6. What trigonometric functions does R provide?

```

```{r 5.6}
summarise(flights, delay = mean(dep_delay, na.rm = TRUE))
by_day <- group_by(flights, year, month, day)
summarise(by_day, delay = mean(dep_delay, na.rm = TRUE))

by_dest <- group_by(flights, dest)
delay <- summarise(by_dest,
  count = n(),
  dist = mean(distance, na.rm = TRUE),
  delay = mean(arr_delay, na.rm = TRUE)
)
delay <- filter(delay, count > 20, dest != "HNL")

ggplot(data = delay, mapping = aes(x = dist, y = delay)) +
  geom_point(aes(size = count), alpha = 1/3) +
  geom_smooth(se = FALSE)

delays <- flights %>% 
  group_by(dest) %>% 
  summarise(
    count = n(),
    dist = mean(distance, na.rm = TRUE),
    delay = mean(arr_delay, na.rm = TRUE)
  ) %>% 
  filter(count > 20, dest != "HNL")

flights %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay))

flights %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay, na.rm = TRUE))

not_cancelled <- flights %>% 
  filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay))
```

```{r 5.6.3}
delays <- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(
    delay = mean(arr_delay)
  )

ggplot(data = delays, mapping = aes(x = delay)) + 
  geom_freqpoly(binwidth = 10)

batting <- as_tibble(Lahman::Batting)

batters <- batting %>% 
  group_by(playerID) %>% 
  summarise(
    ba = sum(H, na.rm = TRUE) / sum(AB, na.rm = TRUE),
    ab = sum(AB, na.rm = TRUE)
  )

batters %>% 
  filter(ab > 100) %>% 
  ggplot(mapping = aes(x = ab, y = ba)) +
    geom_point() + 
    geom_smooth(se = FALSE)

delays %>% 
  filter(n > 25) %>% 
  ggplot(mapping = aes(x = n, y = delay)) + 
    geom_point(alpha = 1/10)

batters %>% 
  arrange(desc(ba))
```

```{r 5.6.4}
not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(
    avg_delay1 = mean(arr_delay),
    avg_delay2 = mean(arr_delay[arr_delay > 0]) # the average positive delay
  )

not_cancelled %>% 
  group_by(dest) %>% 
  summarise(distance_sd = sd(distance)) %>% 
  arrange(desc(distance_sd))

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(
    first = min(dep_time),
    last = max(dep_time)
  )

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(
    first_dep = first(dep_time), 
    last_dep = last(dep_time)
  )

not_cancelled %>% 
  group_by(year, month, day) %>% 
  mutate(r = min_rank(desc(dep_time))) %>% 
  filter(r %in% range(r))

not_cancelled %>% 
  group_by(dest) %>% 
  summarise(carriers = n_distinct(carrier)) %>% 
  arrange(desc(carriers))

not_cancelled %>% 
  count(dest)

not_cancelled %>% 
  count(tailnum, wt = distance)

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(n_early = sum(dep_time < 500))

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(hour_perc = mean(arr_delay > 60))
```

```{r 5.6.5}
daily <- group_by(flights, year, month, day)
(per_day   <- summarise(daily, flights = n()))

(per_month <- summarise(per_day, flights = sum(flights)))

(per_year  <- summarise(per_month, flights = sum(flights)))

daily %>% 
  ungroup() %>%             # no longer grouped by date
  summarise(flights = n())  # all flights
```

```{r 5.6.7 exercises}
# 1. Brainstorm at least 5 different ways to assess the typical delay characteristics of a group of flights. Consider the following scenarios:

#A flight is 15 minutes early 50% of the time, and 15 minutes late 50% of the time.

#A flight is always 10 minutes late.

#A flight is 30 minutes early 50% of the time, and 30 minutes late 50% of the time.

#99% of the time a flight is on time. 1% of the time it’s 2 hours late.

#Which is more important: arrival delay or departure delay?

# 2. Come up with another approach that will give you the same output as not_cancelled %>% count(dest) and not_cancelled %>% count(tailnum, wt = distance) (without using count()).

# 3. Our definition of cancelled flights (is.na(dep_delay) | is.na(arr_delay) ) is slightly suboptimal. Why? Which is the most important column?

# 4. Look at the number of cancelled flights per day. Is there a pattern? Is the proportion of cancelled flights related to the average delay?

# 5. Which carrier has the worst delays? Challenge: can you disentangle the effects of bad airports vs. bad carriers? Why/why not? (Hint: think about flights %>% group_by(carrier, dest) %>% summarise(n()))

# 6. What does the sort argument to count() do. When might you use it?
```

```{r 5.7}
flights_sml %>% 
  group_by(year, month, day) %>%
  filter(rank(desc(arr_delay)) < 10)

popular_dests <- flights %>% 
  group_by(dest) %>% 
  filter(n() > 365)
popular_dests

popular_dests %>% 
  filter(arr_delay > 0) %>% 
  mutate(prop_delay = arr_delay / sum(arr_delay)) %>% 
  select(year:day, dest, arr_delay, prop_delay)
```

```{r 5.7.1}
#1 Refer back to the lists of useful mutate and filtering functions. Describe how each operation changes when you combine it with grouping.

#2 Which plane (tailnum) has the worst on-time record?

#3 What time of day should you fly if you want to avoid delays as much as possible?

#4 For each destination, compute the total minutes of delay. For each flight, compute the proportion of the total delay for its destination.

#5 Delays are typically temporally correlated: even once the problem that caused the initial delay has been resolved, later flights are delayed to allow earlier flights to leave. Using lag(), explore how the delay of a flight is related to the delay of the immediately preceding flight.

#6 Look at each destination. Can you find flights that are suspiciously fast? (i.e. flights that represent a potential data entry error). Compute the air time a flight relative to the shortest flight to that destination. Which flights were most delayed in the air?

#7 Find all destinations that are flown by at least two carriers. Use that information to rank the carriers.

#8 For each plane, count the number of flights before the first delay of greater than 1 hour.
```

